export const galleryPhotos = [
  {
    "src": "/src/img/1.jpg",
    "width": 1800,
    "height": 2585,
    "title": "Herbst II",
    "titleEn": "Autumn II",
    "description": "Hier in Europa, findet man diesen schönen Baum hauptsächlich in der Südtürkei und auf der griechischen Insel Rhodos.  Schätzungen zufolge ist das Verbreitungsgebiet dieser Art in den letzten 200 Jahren von 7000 Hektar auf 1657 Hektar zurückgegangen. Das Harz des Baumes wird seit über 700 Jahren als Allzweckheilmittel verwendet. Früher war es die Harzernte, die eine große Bedrohung für den Orientalischer Amberbaum darstelle. Heute führt die Zerstörung seines Lebensraums zu einem besorgniserregenden Bestandsrückgang. Entwaldung ist ein großes Problem, bedingt durch die intensive Stadtentwicklung und den Bedarf an Platz für Sommerhäuser und Zweitwohnungen (viele Einwohner sind in die Städte gezogen). Man könnte sagen, seine neuen Feinde sind Tourismus und Bebauung. Der Orientalischer Amberbaum steht nun auf der Roten Liste der IUCN (gefährdet, VU).(Quellen: de.wikipedia.org, www.sciencedirect.com,  http://journals.tubitak.gov.tr)",
    "descriptionEn": "In Europe, this beautiful tree is found mainly in southern Turkey and on the Greek island of Rhodes. Its range has shrunk dramatically over the past 200 years, from around 7,000 hectares to 1,657 hectares. The tree’s resin has been used for over 700 years as a remedy; historically resin harvesting threatened the species, but today habitat destruction drives a worrying decline. Deforestation linked to urban development and the demand for summer houses and second homes are major pressures — in short, tourism and construction are its new enemies. The Oriental sweetgum is now listed by the IUCN as Vulnerable (VU).",
    "author": "Sue Hénon",
    "plantCommonName": "Orientalischer Amberbaum",
    "plantCommonNameEn": "Oriental Sweetgum",
    "plantBotanicalName": "Liquidambar orientalis",
    "artworkYear": "2024",
    "artworkSize": "50×70cm",
    "artworkTechnique": "Farbstift auf Papier",
    "artworkTechniqueEn": "Colored pencil on paper",
    "contactEmail": "atelierhenon@googlemail.com",
    "contactPhone": "06071-21613",
    "lowSrc": "/src/thumbs/1.jpg",
    "lowWidth": 400,
    "lowHeight": 575
  },
  {
    "src": "/src/img/2.jpg",
    "width": 1800,
    "height": 2545,
    "title": "Aerangis Punctata",
    "titleEn": "Aerangis Punctata",
    "description": "Aerangis punctata ist eine seltene, auf Bäumen wachsende Orchidee aus den feuchten Hochwäldern Madagaskars. Ihr zartes Gleichgewicht mit dem Lebensraum ist durch Abholzung und Klimaveränderungen bedroht. Um die wenigen verbliebenen Populationen zu schützen, steht sie heute als gefährdete Art (vulnerable) unter internationalem Schutz.",
    "descriptionEn": "Aerangis punctata is a rare, epiphytic orchid from the humid montane forests of Madagascar. Its delicate balance with its habitat is threatened by deforestation and climate change. To protect the few remaining populations, it is listed internationally as Vulnerable.",
    "author": "Kristin Tessen",
    "plantCommonName": "gepunktete Aerangis",
    "plantCommonNameEn": "Spotted Aerangis",
    "plantBotanicalName": "Aerangis punctata ",
    "artworkYear": "2025",
    "artworkSize": "29.7×42cm",
    "artworkTechnique": "Aquarell",
    "artworkTechniqueEn": "Watercolor",
    "contactWebsite": "https://www.instagram.com/kristintessen/",
    "lowSrc": "/src/thumbs/2.jpg",
    "lowWidth": 400,
    "lowHeight": 566
  },
  {
    "src": "/src/img/3.jpg",
    "width": 1800,
    "height": 2546,
    "title": "Round leaved sundew",
    "titleEn": "Round-leaved Sundew",
    "description": "Drosera rotundifolia, der Rundblättrige Sonnentau, ist eine mehrjährige, fleischfressende Pflanze. Sie besiedelt offene, feuchte und nährstoffarme Standorte wie saure Hochmoore und wächst insbesondere in Pflanzengesellschaften, die von Torfmoosen (Sphagnum) dominiert werden.\n\nHochmoore reagieren äußerst empfindlich auf Veränderungen. Entwässerung und Nährstoffeintrag zerstören ihre ökologische Funktion für Artenschutz und Klima. Die Zerstörung in kurzer Zeit machte zunichte, was über Jahrtausende entstand. Die Wiederherstellung der Moore zielt daher auf natürliche Bedingungen – vor allem einen intakten Wasserhaushalt – und benötigt gezielte Impulse und viel Zeit.\n",
    "descriptionEn": "Drosera rotundifolia, the round-leaved sundew, is a perennial carnivorous plant. It inhabits open, wet, nutrient-poor sites such as acidic raised bogs and grows particularly in plant communities dominated by peat mosses (Sphagnum).\n\nRaised bogs are extremely sensitive to change. Drainage and nutrient input destroy their ecological functions for biodiversity and climate. What formed over millennia has been destroyed in a short time. Bog restoration therefore aims to re-establish natural conditions — above all an intact water balance — and requires targeted actions and plenty of time.",
    "author": "Audrey Reilly",
    "plantCommonName": "Rundblättriger Sonnentau",
    "plantCommonNameEn": "Round-leaved Sundew",
    "plantBotanicalName": "Drosera rotundifolia L.",
    "artworkYear": "2024",
    "artworkSize": "34×41cm",
    "artworkTechnique": "Aquarell auf Papier",
    "artworkTechniqueEn": "Watercolor on paper",
    "contactWebsite": "www.audreyreilly-art.com",
    "contactSocial": "@audrey.reilly",
    "lowSrc": "/src/thumbs/3.jpg",
    "lowWidth": 400,
    "lowHeight": 566
  },
  {
    "src": "/src/img/4.jpg",
    "width": 1800,
    "height": 2546,
    "title": "Bog rosemary",
    "titleEn": "Bog Rosemary",
    "description": "Andromeda polifolia, die Rosmarinheide, wächst ausschließlich in Hochmooren kälterer Regionen. Der kleine, immergrüne Zwergstrauch mit zierlichen rosa Blüten ist in den nördlichen Gebieten Nordamerikas, Asiens und Europas verbreitet.\n\nIhr Bestand geht jedoch stark zurück - in England und Irland ist die Art bereits stark dezimiert. Der Lebensraum Hochmoor hat unter Entwässerung, Aufforstung und Torfabbau gelitten, was die Rosmarinheide immer seltener werden lässt. Ihr Verschwinden in Westeuropa ist meist eine direkte Folge der Moorentwässerung.\n\nHochmoore reagieren äußerst empfindlich. Entwässerung zerstört ihre ökologische Funktion für Artenschutz und Klima. Was über Jahrtausende entstand, wurde in kurzer Zeit zerstört. Die Wiederherstellung der Moore benötigt daher natürliche Bedingungen – vor allem einen intakten Wasserhaushalt – und braucht gezielte Maßnahmen sowie viel Zeit.\n",
    "descriptionEn": "Andromeda polifolia, bog rosemary, grows exclusively in raised bogs of cooler regions. This small evergreen shrub with delicate pink flowers is found in northern North America, Asia, and Europe.\n\nIts populations are declining sharply — in England and Ireland it has already been greatly reduced. The bog habitat has suffered from drainage, afforestation, and peat extraction, making bog rosemary ever rarer. Its disappearance in Western Europe is mostly a direct consequence of bog drainage.\n\nRaised bogs are extremely sensitive. Drainage destroys their ecological functions for biodiversity and climate. What formed over millennia has been destroyed in a short time. Restoring bogs requires natural conditions — above all an intact water balance — plus targeted measures and time.",
    "author": "Audrey Reilly",
    "plantCommonName": "Rosmarinheide",
    "plantCommonNameEn": "Bog Rosemary",
    "plantBotanicalName": "Andromeda polifolia",
    "artworkYear": "2024",
    "artworkSize": "34×41cm",
    "artworkTechnique": "Aquarell auf Papier",
    "artworkTechniqueEn": "Watercolor on paper",
    "contactWebsite": "www.audreyreilly-art.com",
    "lowSrc": "/src/thumbs/4.jpg",
    "lowWidth": 400,
    "lowHeight": 566
  },
  {
    "src": "/src/img/5.jpg",
    "width": 1800,
    "height": 2219,
    "title": "Purple Marshlock (Blume des Jahres 2025)",
    "titleEn": "Purple Marshlock (Flower of the Year 2025)",
    "description": "Das Sumpf-Blutauge kommt vom Tiefland bis ins Gebirge vor und besiedelt bevorzugt nasse, zeitweise überflutete Torf- und Schlammböden in Niedermooren. Es gedeiht besonders auf offenen Schlammstellen, wo es sich mit seinem langen Wurzelstock gut ausbreiten kann. Sogar auf Schwingrasen bildet es allmählich schwankende Teppiche auf der Wasseroberfläche mooriger Gewässer.\n\nAls Spezialist für den stark bedrohten Lebensraum Moor steht die Art in vielen Regionen auf der Roten Liste. Die Loki Schmidt Stiftung hat sie zur Blume des Jahres 2025 ernannt.\n\nHochmoore reagieren äußerst empfindlich auf Störungen. Entwässerung und Nährstoffeintrag zerstören ihre ökologischen Funktionen für Artenschutz und Klima. Was über Jahrtausende entstand, wurde in kurzer Zeit zerstört. Die Wiederherstellung der Moore zielt daher auf natürliche Bedingungen – besonders einen intakten Wasserhaushalt – und benötigt gezielte Maßnahmen und viel Zeit.",
    "descriptionEn": "Purple marshlock (Comarum palustre) occurs from lowland to mountain regions and colonizes wet, periodically flooded peat and mud soils in fens. It thrives especially on open mud patches, where its long rhizome allows it to spread well, even forming floating mats on quaking bog surfaces.\n\nAs a specialist of the highly threatened moor habitat, it is Red-Listed in many regions. The Loki Schmidt Foundation named it Flower of the Year 2025.\n\nRaised bogs are extremely sensitive to disturbance. Drainage and nutrient input destroy their ecological functions for biodiversity and climate. What formed over millennia has been destroyed in a short time. Restoration aims to re-establish natural conditions — especially an intact water balance — and requires targeted measures and time.",
    "author": "Audrey Reilly",
    "plantCommonName": "Blutauge, Sumpf-Fingerkraut",
    "plantCommonNameEn": "Purple Marshlock, Marsh Cinquefoil",
    "plantBotanicalName": "Comarum palustre",
    "artworkYear": "2024",
    "artworkSize": "40×50cm",
    "artworkTechnique": "Aquarell auf Papier",
    "artworkTechniqueEn": "Watercolor on paper",
    "contactWebsite": "www.audreyreilly-art.com",
    "lowSrc": "/src/thumbs/5.jpg",
    "lowWidth": 400,
    "lowHeight": 493
  },
  {
    "src": "/src/img/6.png",
    "width": 1800,
    "height": 1350,
    "title": "Echte Lungenflechte ",
    "titleEn": "Tree Lungwort",
    "description": "Durch Luftverschmutzung und die Zerstörung ihrer Lebensräume u. a. durch intensive forstwirtschaftliche Nutzung steht die Echte Lungenflechte mittlerweile in Deutschland auf der Roten Liste und gilt als \"Vom Aussterben bedroht\".\nDenn sie benötigt sehr saubere Luft, alte Bäume und eine hohe Luftfeuchtigkeit, um zu gedeihen. ",
    "descriptionEn": "Due to air pollution and the destruction of its habitats — including intensive forestry — tree lungwort is now on Germany’s Red List and considered \"critically endangered\". It requires very clean air, old trees, and high humidity to thrive.",
    "author": "Katrin Koch ",
    "plantCommonName": "Echte Lungenflechte ",
    "plantCommonNameEn": "Tree Lungwort",
    "plantBotanicalName": "Lobaria pulmonaria ",
    "artworkYear": "2025",
    "artworkSize": "7.5×26cm",
    "artworkTechnique": "Graphit und Farbstift auf Papier /Fabriano Artistico Hot Pressed \"Extra White\" ",
    "artworkTechniqueEn": "Graphite and colored pencil on paper / Fabriano Artistico Hot Pressed \"Extra White\"",
    "contactEmail": "malusred@gmx.de",
    "lowSrc": "/src/thumbs/6.jpg",
    "lowWidth": 533,
    "lowHeight": 400
  },
  {
    "src": "/src/img/9.png",
    "width": 1800,
    "height": 2250,
    "title": "Der Stern der Alpen",
    "titleEn": "The Star of the Alps",
    "description": "Das Edelweiß ist in seinem natürlichen Lebensraum nach wie vor durch übertriebenes Pflücken bedroht. An vielen leicht zugänglichen Standorten war es dadurch fast ausgestorben. Seit die Art in vielen Ländern und Regionen unter Naturschutz steht, haben sich die Bestände in der freien Natur erholt. Die wilden Pflanzen sind jedoch nach wie vor durch unkontrolliertes Sammeln und Lebensraumverlust bedroht.\n\nDie Pflanze wird gerne in vielen Gärten kultiviert. Kulturpflanzen sehen im Vergleich zu Wildpflanzen meist anders aus. Sie sind oft deutlich höher und weniger weiß behaart. Die hier abgebildete Pflanze ist ein Kulturexemplar.",
    "descriptionEn": "Edelweiss remains threatened in its natural habitat by excessive picking. At many easily accessible sites it had nearly disappeared. Since the species gained protection in many countries and regions, wild populations have recovered, yet wild plants are still threatened by uncontrolled collecting and habitat loss.\n\nThe plant is widely cultivated in gardens. Cultivars often look different from wild plants — typically taller and less densely white-haired. The specimen shown here is cultivated.",
    "author": "Maxim Shirshin",
    "plantCommonName": "Alpen-Edelweiß",
    "plantCommonNameEn": "Alpine Edelweiss",
    "plantBotanicalName": "Leontopodium nivale",
    "artworkYear": "2025",
    "artworkSize": "21×29.7cm",
    "artworkTechnique": "Buntstifte auf Papier",
    "artworkTechniqueEn": "Colored pencils on paper",
    "contactPhone": "+447376444778",
    "contactEmail": "max.shirshin@gmail.com",
    "contactSocial": "max.shirshin",
    "lowSrc": "/src/thumbs/9.png",
    "lowWidth": 400,
    "lowHeight": 500
  },
  {
    "src": "/src/img/13.jpg",
    "width": 1800,
    "height": 2250,
    "title": "Frauenschuh",
    "titleEn": "Lady's Slipper Orchid",
    "description": "Der Frauenschuh gilt nach der Roten Liste als gefährdet und ist nach der Bundesartenschutzverordnung streng geschützt. Er steht auch unter besonderem Schutz der Europäischen Union. \nAls ursächlich für die Gefährdung wird vor allem die weitreichende Forstwirtschaft gesehen, die eine natürliche Waldentwicklung und -dynamik kaum zulässt. Fototourismus trägt zu einem Rückgang der Art bei, da der Boden sich durch häufiges Betreten verdichtet und dadurch neuen Exemplaren eine Ansiedlung erschwert wird. \nAuch Pflanzenliebhaber, die den Frauenschuh ausgraben, tragen wesentlich zum Rückgang der verbliebenen Vorkommen bei.\n (Vgl. https://de.wikipedia.org/wiki/Gelber_Frauenschuh, 08.10.2025)",
    "descriptionEn": "The lady's slipper orchid is classified as endangered on the Red List and is strictly protected under federal species conservation regulations and by the European Union. Extensive forestry, which leaves little room for natural forest dynamics, is a primary cause of endangerment. Photo tourism contributes to the decline as repeated trampling compacts the soil, hindering establishment of new plants. Plant enthusiasts who dig up wild specimens further reduce the remaining populations.",
    "author": "Leslie Bocker",
    "plantCommonName": "Frauenschuh",
    "plantCommonNameEn": "Lady's Slipper Orchid",
    "plantBotanicalName": "Cypripedium calceolus L.",
    "artworkYear": "2025",
    "artworkSize": "25×50cm",
    "artworkTechnique": "Aquarell",
    "artworkTechniqueEn": "Watercolor",
    "contactSocial": "leslie.bocker",
    "lowSrc": "/src/thumbs/13.jpg",
    "lowWidth": 400,
    "lowHeight": 500
  },
  {
    "src": "/src/img/15.jpg",
    "width": 1800,
    "height": 1440,
    "title": "Kastanie",
    "titleEn": "Horse Chestnut",
    "description": "Die Rosskastanie hierzulande hat gleich mit mehreren Problemen auf einmal zu kämpfen: Zum einen mit der sogenannten Miniermotte, zum anderen mit einem Bakterium namens Pseudomonas. Auch der Klimawandel stresst die Bäume zunehmend. Die Weltnaturschutzunion (IUCN) hat die Gewöhnliche Rosskastanie deshalb mittlerweile als \"gefährdet\" eingestuft.\n( https://www.oekotest.de/freizeit-technik/Kastanienblaetter-schon-im-Sommer-braun-So-reagieren-Sie-richtig_12142_1.html, 25.09.2025)",
    "descriptionEn": "The horse chestnut is facing several problems at once: the leaf miner moth, a bacterium called Pseudomonas, and increasing stress from climate change. The IUCN has classified the common horse chestnut as Vulnerable.",
    "author": "Leslie Bocker",
    "plantCommonName": "Gewöhnliche Rosskastanie",
    "plantCommonNameEn": "Common Horse Chestnut",
    "plantBotanicalName": "Aesculus hippocastanum",
    "artworkYear": "2024",
    "artworkSize": "25×23cm",
    "artworkTechnique": "Aquarell",
    "artworkTechniqueEn": "Watercolor",
    "contactSocial": "leslie.bocker",
    "lowSrc": "/src/thumbs/15.jpg",
    "lowWidth": 500,
    "lowHeight": 400
  },
  {
    "src": "/src/img/16.jpg",
    "width": 1800,
    "height": 2388,
    "title": "Maiglöckchen",
    "titleEn": "Lily of the Valley",
    "description": "Diese zarte Blume wächst in vielen europäischen Ländern in der freien Natur, jedoch ist die Anzahl der Pflanzen sehr gering. In vielen Ländern ist das Pfücken der Blumen verboten, wie z.B. im Ruhrgebiet in Deutschland. Obwohl in Deutschland kleine Sträußchen für den Eigenbedarf erlaubt sind, ist das Ausgraben der unterirdischen Teile wie der Rhizome in der freien Natur untersagt, um die Bestände zu erhalten. ",
    "descriptionEn": "This delicate flower grows in the wild in many European countries, yet plant numbers are very low. In many regions, picking the flowers is prohibited, such as in Germany’s Ruhr area. Although small bouquets for personal use are permitted in Germany, digging up underground parts like rhizomes is forbidden in the wild to preserve populations.",
    "author": "Nadiya Kyrylenko",
    "plantCommonName": "Maiglöckchen",
    "plantCommonNameEn": "Lily of the Valley",
    "plantBotanicalName": "Convallaria majalis",
    "artworkYear": "2025",
    "artworkSize": "30×40cm",
    "artworkTechnique": "Mischtechnik: Aquarell und Bleistift",
    "artworkTechniqueEn": "Mixed media: Watercolor and pencil",
    "contactPhone": "01791314354",
    "contactWebsite": "https://www.instagram.com/nadiya_kyrylenko/",
    "lowSrc": "/src/thumbs/16.jpg",
    "lowWidth": 400,
    "lowHeight": 531
  },
  {
    "src": "/src/img/17.jpg",
    "width": 1800,
    "height": 1817,
    "title": "Stille der Frühlingswiesen",
    "titleEn": "Silence of Spring Meadows",
    "description": "Schachblume (Fritillaria meleagris)\nAquarell und Graphit auf Papier\n\nEine seltene, in Deutschland geschützte Art.\nIhre natürlichen Lebensräume – feuchte Wiesen und Flussauen – verschwinden nach und nach, und mit ihnen verschwindet auch die Schachblume.\nZart und zugleich widerstandsfähig verkörpert sie die Idee des Überlebens durch Sanftheit.\nDiese Arbeit ist eine Hommage an ihre stille Schönheit und ihre flüchtige Präsenz in der Natur.",
    "descriptionEn": "Snake's head fritillary (Fritillaria meleagris)\nWatercolor and graphite on paper\n\nA rare species protected in Germany. Its natural habitats — damp meadows and river floodplains — are disappearing, and with them the fritillary itself. Delicate yet resilient, it embodies the idea of surviving through gentleness. This work is a homage to its quiet beauty and fleeting presence in nature.",
    "author": "Lesia Zaitseva",
    "plantCommonName": "Schachblume (Fritillaria meleagris)",
    "plantCommonNameEn": "Snake's Head Fritillary",
    "plantBotanicalName": "Fritillaria meleagris",
    "artworkYear": "2025",
    "artworkSize": "56×56cm",
    "artworkTechnique": "Aquarell und Graphit auf Papier Saunders Waterford HP 425 g/m²",
    "artworkTechniqueEn": "Watercolor and graphite on Saunders Waterford HP 425 gsm paper",
    "contactSocial": "Lesia_botanicalart",
    "lowSrc": "/src/thumbs/17.jpg",
    "lowWidth": 400,
    "lowHeight": 404
  },
  {
    "src": "/src/img/18.jpg",
    "width": 1800,
    "height": 2408,
    "title": "Lion's Tooth (Deutsche Löwenzahn)",
    "titleEn": "Lion's Tooth (German Common Dandelion)",
    "description": "Der deutsche Löwenzahn (Taraxacum germanium), einst Teil der einheimischen Flora Deutschlands, ist heute vom Aussterben bedroht und überlebt nur noch an wenigen verstreuten Standorten in Hessen, Unterfranken und Oberbayern. Die meisten dieser Populationen bestehen aus nur wenigen einzelnen Pflanzen und überschreiten selten fünfzig Exemplare. Diese Art gedeiht in Niederungs-Feuchtwiesen, oft auf leicht salzhaltigen Böden, doch ihre Empfindlichkeit gegenüber Düngung und Störungen des Lebensraums hat sie äußerst verletzlich gemacht. Landwirtschaftliche Intensivierung, Lebensraumverlust und Verschmutzung haben sie an den Rand des Aussterbens gedrängt.\n\nWährend der Gewöhnliche Löwenzahn (Taraxacum officinale) heute noch weit verbreitet ist, werden auch seine natürlichen Lebensräume zunehmend durch ähnliche Bedrohungen – Herbizideinsatz, Monokultur-Landwirtschaft, städtische Bebauung und den Klimawandel – beeinträchtigt. Wenn diese Belastungen anhalten, könnte selbst diese widerstandsfähige und weit verbreitete Pflanze dem Beispiel des deutschen Löwenzahns folgen und zurückgehen – ein mahnendes Zeichen dafür, dass keine Art vor den Folgen menschengemachter Umweltveränderungen gefeit ist.",
    "descriptionEn": "German dandelion (Taraxacum germanicum), once part of Germany’s native flora, is now threatened with extinction, surviving only at scattered sites in Hesse, Lower Franconia, and Upper Bavaria. Most populations consist of very few plants, rarely exceeding fifty. It thrives in lowland wet meadows, often on slightly saline soils, but sensitivity to fertilization and habitat disturbance has left it highly vulnerable. Agricultural intensification, habitat loss, and pollution have pushed it to the brink.\n\nWhile the common dandelion (Taraxacum officinale) remains widespread, its natural habitats are also increasingly affected by similar pressures — herbicides, monoculture agriculture, urban development, and climate change. If these pressures continue, even this resilient species may decline — a reminder that no species is immune to human-driven environmental change.",
    "author": "Kate Rolshoven",
    "plantCommonName": "Deutsche Gewohnliche Löwenzahn",
    "plantCommonNameEn": "German Dandelion",
    "plantBotanicalName": "Taraxacum germanicum",
    "artworkYear": "2023",
    "artworkSize": "56×76cm",
    "artworkTechnique": "Aquarell on Arches 640gsm Baumwollpapier",
    "artworkTechniqueEn": "Watercolor on Arches 640gsm cotton paper",
    "contactWebsite": "www.katerolshovenart.com",
    "contactSocial": "katerolshovenart",
    "lowSrc": "/src/thumbs/18.jpg",
    "lowWidth": 400,
    "lowHeight": 535
  },
  {
    "src": "/src/img/19.jpg",
    "width": 1800,
    "height": 1273,
    "title": "Beta vulgaris",
    "titleEn": "Beta vulgaris",
    "description": "Die wilde Rübe die Urpflanze unseres heutigen Mangolds und der Roten Bete. Die Wildform gilt in Deutschland als potenziell gefährdet. Auf Helgoland, wo sie früher weit verbreitet war, gibt es noch einige wenige Bestände. Die Beta vulgaris wurde sonst nur noch an einigen Orten an der Ostseeküste verzeichnet.",
    "descriptionEn": "The wild beet, ancestor of today’s chard and red beet, is considered potentially threatened in Germany. On Heligoland, where it was once widespread, only a few populations remain. Elsewhere, Beta vulgaris has been recorded only at a handful of sites along the Baltic coast.",
    "author": "Manuela Herhaus",
    "plantCommonName": "Wilde Rübe",
    "plantCommonNameEn": "Wild Beet",
    "plantBotanicalName": "Beta vulgaris subsp. maritima",
    "artworkYear": "2025",
    "artworkSize": "30×42cm",
    "artworkTechnique": "Tusche auf Zeichenfolie mit Beschreibung auf Papier",
    "artworkTechniqueEn": "Ink on drafting film with description on paper",
    "contactEmail": "herhaus@wortimpulse.de",
    "lowSrc": "/src/thumbs/19.jpg",
    "lowWidth": 566,
    "lowHeight": 400
  },
  {
    "src": "/src/img/22.png",
    "width": 1443,
    "height": 1337,
    "title": "Deutsche Ufertamariske - Früchte und Samen",
    "titleEn": "German River Tamarisk – Fruits and Seeds",
    "description": "Die dynamischen, regelmäßig überschotterten Ufer alpiner Wildflüsse – die natürlichen Lebensräume der Deutschen Tamariske – sind durch umfassende Flussregulierungen fast vollständig zerstört worden. Ohne diese natürliche Gewässerdynamik breiten sich Weiden und Erlen aus und verdrängen die Tamariske. Deshalb wird die Art in der Roten Liste Deutschlands als „vom Aussterben bedroht“ geführt und kommt nur noch in wenigen stark beeinträchtigten Resthabitaten vor.",
    "descriptionEn": "The dynamic, regularly gravel-covered banks of alpine wild rivers — the natural habitats of the German tamarisk — have been almost completely destroyed by extensive river regulation. Without natural river dynamics, willows and alders spread and outcompete the tamarisk. As a result, the species is listed in Germany’s Red List as critically endangered and persists only in a few heavily impacted remnant habitats.",
    "author": "Elisabeth Lázár ",
    "plantCommonName": "Deutsche Tamariske",
    "plantCommonNameEn": "German Tamarisk",
    "plantBotanicalName": "Myricaria germanica",
    "artworkYear": "2025",
    "artworkSize": "29×29cm",
    "artworkTechnique": "Graphit, Papier",
    "artworkTechniqueEn": "Graphite, paper",
    "lowSrc": "/src/thumbs/22.jpg",
    "lowWidth": 432,
    "lowHeight": 400
  },
  {
    "src": "/src/img/23.png",
    "width": 1800,
    "height": 2286,
    "title": "Karlszepter-Läusekraut - Kapselfrucht",
    "titleEn": "King's Scepter Lousewort – Capsule Fruit",
    "description": "Die Samen des Karlszepters reifen in den charakteristischen Kapselfrüchten. Die Keimung gelingt nur auf dauerhaft nassen, torfigen Moorböden, weshalb sich die Art nur sehr begrenzt ausbreiten kann. Als halbparasitische Pflanze ist sie auf die Wurzeln bestimmter Wirtsarten angewiesen, was ihre erfolgreiche Etablierung zusätzlich einschränkt.",
    "descriptionEn": "The seeds of the king’s scepter ripen in characteristic capsule fruits. Germination succeeds only on permanently wet, peaty bog soils, which greatly limits the species’ ability to spread. As a hemiparasitic plant, it depends on the roots of specific host species, further constraining successful establishment.",
    "author": "Elisabeth Lázár",
    "plantCommonName": "Karlszepter-Läusekraut",
    "plantCommonNameEn": "King's Scepter Lousewort",
    "plantBotanicalName": "Pedicularis sceptrum-carolinum L.",
    "artworkYear": "2025",
    "artworkSize": "21×27cm",
    "artworkTechnique": "Tinte, Papier",
    "artworkTechniqueEn": "Ink, paper",
    "lowSrc": "/src/thumbs/23.png",
    "lowWidth": 400,
    "lowHeight": 508
  },
  {
    "src": "/src/img/24.png",
    "width": 1800,
    "height": 2660,
    "title": "Karlszepter-Läusekraut - Grundblätter und Kapselfrüchte",
    "titleEn": "King's Scepter Lousewort – Basal Leaves and Capsule Fruits",
    "description": "Das Karlszepter ist ein seltenes Relikt der Eiszeit und gilt daher als besonders wertvoll für die botanische Vielfalt. Es bevorzugt nährstoffarme Moorwiesen, Flachmoore und feuchte Wegränder, Lebensräume, die durch Entwässerung, Nutzungsänderungen und Klimawandel stark zurückgegangen sind. Dadurch ist die Art in vielen südlichen Regionen selten geworden und gilt heute als stark gefährdet. Ihre besondere ökologische Rolle als typische Moorart macht sie zu einem wichtigen Indikator für intakte, besonders empfindliche Feuchtökosysteme.",
    "descriptionEn": "The king’s scepter is a rare Ice Age relict and thus particularly valuable for botanical diversity. It favors nutrient-poor moor meadows, fens, and damp path edges — habitats that have strongly declined due to drainage, land-use change, and climate change. Consequently, the species has become rare in many southern regions and is now considered highly endangered. Its ecological role as a typical moor species makes it an important indicator of intact, highly sensitive wetland ecosystems.",
    "author": "Elisabeth Lázár ",
    "plantCommonName": "Karlszepter-Läusekraut",
    "plantCommonNameEn": "King's Scepter Lousewort",
    "plantBotanicalName": "Pedicularis sceptrum-carolinum L.",
    "artworkYear": "2025",
    "artworkSize": "28×42cm",
    "artworkTechnique": "Aquarell, Graphit, Papier",
    "artworkTechniqueEn": "Watercolor, graphite, paper",
    "lowSrc": "/src/thumbs/24.jpg",
    "lowWidth": 400,
    "lowHeight": 591
  },
  {
    "src": "/src/img/25.jpg",
    "width": 1365,
    "height": 2048,
    "title": "Geweihförmige Wiesenkoralle ",
    "titleEn": "Antler-shaped Meadow Coral",
    "description": "Durch die intensive Nutzung ihres speziellen Lebensraumes - dem Magerrasen, gingen die Bestände dieser Art in den letzten Jahrzehnten deutlich zurück und die Geweihförmige Wiesenkoralle steht mittlerweile als \"Gefährdet\" auf der Roten Liste in Deutschland.\nDenn Überdüngung, Bebauung und Überwässerung verändert ihr Ökosystem und so ist der Lebensraum mittlerweile nur noch selten in unserer Landschaft zu finden. ",
    "descriptionEn": "Due to intensive use of its specific habitat — nutrient-poor grasslands — populations of this species have declined markedly in recent decades, and the antler-shaped meadow coral is now listed as \"Vulnerable\" on Germany’s Red List. Over-fertilization, construction, and over-watering alter its ecosystem, making its habitat increasingly rare in our landscape.",
    "author": "Katrin Koch ",
    "plantCommonName": "Geweihförmige Wiesenkoralle ",
    "plantCommonNameEn": "Antler-shaped Meadow Coral",
    "plantBotanicalName": "Clavulinopsis corniculata",
    "artworkYear": "2025",
    "artworkSize": "11×11.8cm",
    "artworkTechnique": "Farbstift auf Papier /Fabriano Artistico Hot Pressed \"Extra White\" ",
    "artworkTechniqueEn": "Colored pencil on paper / Fabriano Artistico Hot Pressed \"Extra White\"",
    "contactEmail": "malusred@gmx.de",
    "lowSrc": "/src/thumbs/25.jpg",
    "lowWidth": 400,
    "lowHeight": 600
  },
  {
    "src": "/src/img/26.jpg",
    "width": 1800,
    "height": 1361,
    "title": "Vom Blühen und Reifen",
    "titleEn": "On Blooming and Ripening",
    "description": "Die Preiselbeere begleitet mich seit meiner Kindheit. Als ich im Sommer im Norden war, wuchsen sie dort in unglaublicher Fülle – ganze Teppiche aus kleinen, glänzenden Blättern und tiefroten Beeren. Für mich trägt diese Pflanze deshalb eine ganz eigene, nostalgische Wärme. Heute jedoch ist ihr Lebensraum in Deutschland und vielen Teilen Europas stark geschrumpft. Moore, Heiden und lichte Kiefernwälder, in denen die Preiselbeere einst heimisch war, verschwinden durch Entwässerung, Aufforstung, Landwirtschaft und den Klimawandel. In manchen Regionen Europas ist die Art bereits deutlich zurückgegangen.\nWas oft übersehen wird: Ihr Rückgang betrifft nicht nur die Pflanze selbst, sondern auch das Netzwerk an Leben um sie herum. Die Blüten der Preiselbeere werden vor allem von Hummeln und verschiedenen Wildbienen bestäubt – Insekten, deren Populationen ebenfalls unter Druck stehen. Wenn ihre Bestäuber seltener werden, sinkt auch die Fruchtbildung der Preiselbeere. Beide Seiten verlieren also gemeinsam ihren Platz.\nMit meinem Bild möchte ich diese leise, doch bedeutende Verbindung sichtbar machen: die Verwundbarkeit der Preiselbeere und die fragile Gemeinschaft, die sie trägt – und die sie zugleich braucht, um weiter zu bestehen.",
    "descriptionEn": "Lingonberry has accompanied me since childhood, growing in incredible abundance in the north — carpets of small, glossy leaves and deep red berries. Today its habitats in Germany and across Europe have shrunk. Bogs, heaths, and open pine forests are disappearing due to drainage, afforestation, agriculture, and climate change. This decline affects the plant and its pollinators — mainly bumblebees and wild bees. As pollinators become rarer, fruit set falls; both lose their place together. This painting aims to show that quiet, significant connection: the vulnerability of lingonberry and the fragile community it supports and needs.",
    "author": "Daria Beizerov",
    "plantCommonName": "Preiselbeere",
    "plantCommonNameEn": "Lingonberry",
    "plantBotanicalName": "Vaccinium vitis-idaea",
    "artworkYear": "2025",
    "artworkSize": "41×31cm",
    "artworkTechnique": "Aquarell auf Papier (HP)",
    "artworkTechniqueEn": "Watercolor on paper (HP)",
    "contactWebsite": "https://daria.gallery",
    "contactSocial": "https://www.instagram.com/daria.botanicals/",
    "lowSrc": "/src/thumbs/26.jpg",
    "lowWidth": 529,
    "lowHeight": 400
  },
  {
    "src": "/src/img/28.jpg",
    "width": 1800,
    "height": 2195,
    "title": "Weiße Schlauchpflanze",
    "titleEn": "White Pitcher Plant",
    "description": "Die Weiße Schlauchpflanze (Sarracenia leucophylla) kommt ursprünglich im Südosten der Vereinigten Staaten vor, insbesondere in Alabama, Georgia, Florida und Mississippi. Obwohl sie dort noch in der Wildnis vorkommt, ist sie durch das Sammeln zu Dekorationszwecken und durch Landentwicklung bedroht. Daher ist sie in der Roten Liste der bedrohten Arten der IUCN aufgeführt. Als Zimmerpflanze ist sie beliebt, weil sie mit ihren auffällig gezeichneten Schläuchen und ihrer Fähigkeit, Insekten zu fangen, ein außergewöhnliches und dekoratives Element darstellt.",
    "descriptionEn": "The white pitcher plant (Sarracenia leucophylla) is native to the southeastern United States, especially Alabama, Georgia, Florida, and Mississippi. Though it still occurs in the wild, it is threatened by collection for decorative use and by land development. It is listed on the IUCN Red List. As a houseplant, it is popular for its strikingly patterned pitchers and its ability to capture insects.",
    "author": "Sophie Crossart",
    "plantCommonName": "Weiße Schlauchpflanze",
    "plantCommonNameEn": "White Pitcher Plant",
    "plantBotanicalName": "Sarracenia leucophylla",
    "artworkYear": "2025",
    "artworkSize": "17×20cm",
    "artworkTechnique": "Aquarell und ein wenig Gouache auf Kalbsvellum",
    "artworkTechniqueEn": "Watercolor and a touch of gouache on calf vellum",
    "contactEmail": "contact@sophiecrossart.com",
    "contactWebsite": "www.sophiecrossart.com",
    "contactSocial": "sophiecrossart",
    "lowSrc": "/src/thumbs/28.jpg",
    "lowWidth": 400,
    "lowHeight": 487
  },
  {
    "src": "/src/img/29.png",
    "width": 1800,
    "height": 2547,
    "title": "Zahnbürstchenwiese",
    "titleEn": "Toothbrush Meadow",
    "description": "Der Schlangenknöterich ist eine typische Pflanze feuchter, artenreicher Lebensräume. Er wächst bevorzugt in Feuchtwiesen, an den Ufern von Bächen, an Moorrändern sowie in lichten Auwäldern. Doch sind diese Lebensräume zunehmend im Rückgang begriffen. \nTrockenlegungen, intensive Bewirtschaftung durch die Landwirtschaft und das Verschwinden naturnaher Auwälder führen zum Verlust geeigneter Standorte. \nHinzu kommen die Auswirkungen des Klimawandels.\nDer Schlangenknöterich steht in Bayern auf Platz 3 der Gefährdungsliste.\nSo wird er zunehmend zum Symbol für die bedrohte Schönheit unserer Feuchtlandschaften.",
    "descriptionEn": "Common bistort is a characteristic plant of wet, species-rich habitats. It favors wet meadows, stream banks, bog margins, and open floodplain forests. These habitats are increasingly in decline due to drainage, intensive agriculture, and the loss of near-natural floodplain forests, compounded by climate change. In Bavaria, common bistort ranks third on the threat list, symbolizing the endangered beauty of our wetlands.",
    "author": "Susanne Jampen",
    "plantCommonName": "Schlangenknöterich",
    "plantCommonNameEn": "Common Bistort",
    "plantBotanicalName": "Bistorta officinalis",
    "artworkYear": "Sommer 2025",
    "artworkSize": "20×32cm",
    "artworkTechnique": "Aquarell auf Fabriano artistico hot press",
    "artworkTechniqueEn": "Watercolor on Fabriano Artistico hot press",
    "contactEmail": "s.jampen@icloud.com",
    "lowSrc": "/src/thumbs/29.png",
    "lowWidth": 400,
    "lowHeight": 566
  },
  {
    "src": "/src/img/30.jpg",
    "width": 1800,
    "height": 2342,
    "title": "Sumpf-Herzblatt",
    "titleEn": "Marsh Grass-of-Parnassus",
    "description": "Diese seltene Pflanze gehört zu den Steinbrech-Gewächsen und steht auf der Roten Liste Bayerns und gilt als gefährdet. Ursache für die Gefährdung der Pflanze sind etwa die Entwässerung und Aufforstung von Moor-Standorten oder Trockenlegungen von Feuchtwiesen. Aber auch durch die Eutrophierungen, sprich Dünger-Eintragungen, werde die konkurrenzschwache Art zurückgedrängt (https://pfaffenhofen-today.de/46272-p-serie-sumpf-herzblatt. 08.10.2025)",
    "descriptionEn": "This rare plant belongs to the saxifrage family and is listed as endangered on Bavaria’s Red List. Threats include drainage and afforestation of bog sites, and the drying of wet meadows. Eutrophication — i.e., fertilizer inputs — also pushes back this weak competitor.",
    "author": "Leslie Bocker",
    "plantCommonName": "Sumpf-Herzblatt",
    "plantCommonNameEn": "Marsh Grass-of-Parnassus",
    "plantBotanicalName": "Parnassia palustris",
    "artworkYear": "2025",
    "artworkSize": "31×39cm",
    "artworkTechnique": "Aquarell",
    "artworkTechniqueEn": "Watercolor",
    "contactSocial": "leslie.bocker",
    "lowSrc": "/src/thumbs/30.jpg",
    "lowWidth": 400,
    "lowHeight": 520
  },
  {
    "src": "/src/img/31.png",
    "width": 1427,
    "height": 2008,
    "title": "Die Geneigte",
    "titleEn": "The Leaning One",
    "description": "Die Bach-Nelkenwurz ist eine typische Pflanze in feuchten Lebensräumen. Sie wächst in Flachmooren, Feuchtwiesen, an Bächen und Teichufern und am Rande von Auwäldern.\nTrotz ihres ursprünglich großen Verbreitungsareals gilt die Bach-Nelkenwurz in mehreren deutschen Bundesländern mittlerweile als gefährdet und ist dort auf den regionalen roten Listen verzeichnet. \nDie Hauptursachen dafür liegen in der Zerstörung und Veränderung der Lebensräume.\nDie Trockenlegung von Feuchtgebieten, die Intensivnutzung der Wiesen, und das Verschwinden der naturnahen Auwälder führen zu einem drastischen Rückgang der Standorte. Dazu kommen die durch den Klimawandel veränderten Niederschlagsmuster und die steigenden Temperaturen, die zur Austrocknung der Lebensräume beitragen.",
    "descriptionEn": "Water avens is a typical plant of wet habitats — fens, wet meadows, stream and pond margins, and floodplains. Despite its formerly broad range, it is now considered threatened in several German states and appears on regional Red Lists. Draining wetlands, intensive meadow use, and the loss of near-natural floodplain forests, together with climate-change-driven shifts in precipitation and higher temperatures, are driving habitat decline.",
    "author": "Susanne Jampen",
    "plantCommonName": "Bach-Nelkenwurz",
    "plantCommonNameEn": "Water Avens",
    "plantBotanicalName": "Geum rivale",
    "artworkYear": "Sommer 2024",
    "artworkSize": "20×32cm",
    "artworkTechnique": "Aquarell auf Fabriano Artistico hot pressd ",
    "artworkTechniqueEn": "Watercolor on Fabriano Artistico hot pressed",
    "contactEmail": "s.jampen@icloud.com",
    "lowSrc": "/src/thumbs/31.jpg",
    "lowWidth": 400,
    "lowHeight": 563
  },
  {
    "src": "/src/img/32.png",
    "width": 1600,
    "height": 1200,
    "title": "Enzian",
    "titleEn": "Gentian",
    "description": "Gentiana acaulis gehört zur Familie der Enziangewächse (Gentianaceae) und ist in Bergregionen Mittel- und Südeuropas heimisch, insbesondere in den Alpen aber auch im Jura und den Pyrenäen. Dieser Enzian wächst in Höhen von 800 bis 3000 m auf gut mit Wasser versorgten Silikatböden. Ein besonderes Kennzeichen von Gentiana acaulis sind kurze Blütenstände, die aus den grundständigen dichten Blattrosetten zu entspringen scheinen. Die intensiv blauen Blüten locken zur Blütezeit von April bis Juni Hummeln und Schmetterlinge zur Bestäubung an.\nDie natürlichen Lebensräume nehmen auch für den Kiesel-Glocken-Enzian immer mehr ab, weil auch die Bergwiesen immer häufiger überdüngt sind. Schon eine Portion Gülle vertreibt die Pflanze in kurzer Zeit und danach bleibt sie auch für Jahrzehnte noch verschwunden. Gentiana acaulis steht wie alle Enzianarten unter Naturschutz und ist in der Roten Liste als gefährdet eingestuft.",
    "descriptionEn": "Gentiana acaulis belongs to the gentian family and is native to mountainous regions of Central and Southern Europe, especially the Alps. It grows from 800–3000 m on well-watered silicate soils. Short flower stalks appear to emerge from dense basal rosettes, and the intensely blue flowers attract bumblebees and butterflies from April to June. Its habitats are shrinking due to over-fertilization of mountain meadows. Even a single slurry application can drive it away for years. Like all gentians, it is protected and Red-Listed as endangered.",
    "author": "Brigitte Rückle",
    "plantCommonName": "Kiesel-Glocken-Enzian",
    "plantCommonNameEn": "Trumpet Gentian",
    "plantBotanicalName": "Gentiana acaulis",
    "artworkYear": "2025",
    "artworkSize": "31.5×29.5cm",
    "artworkTechnique": "Buntstifte",
    "artworkTechniqueEn": "Colored pencils",
    "contactNote": "Brigitte Rückle c/o VBKD",
    "lowSrc": "/src/thumbs/32.jpg",
    "lowWidth": 451,
    "lowHeight": 400
  },
  {
    "src": "/src/img/33.png",
    "width": 2629,
    "height": 3440,
    "title": "Platterbse/Duftwicke",
    "titleEn": "Pea-vine / Sweet Pea",
    "description": "Bei meinen Recherchen in Vorbereitung der Ausstellung bin ich auf www.rote-liste-zentrum.de darauf gestossen, dass verschiedene Wildformen, wie z.B. die Lathyrus nissolia L. (Gras-Platterbse) und die Lathyrus heterophyllus L. (Verschiedenblättrige Platterbse) gefährdet sind und die Lathyrus bauhini P.A. Genty (Schwert-Platterbse) sogar vom Aussterben bedroht ist. Es gibt noch einige andere Gefährdete, die man auf der genannten Internetseite finden kann.\nUm dem Sammeln der Samen von Wildformen entgegenzuwirken, bietet der Handel zahlreiche kultivierte Sorten von Platterbsen oder auch Wicken an. Ich mag die bizarren Blüten in den unterschiedlichen Farben sehr gern und so zog ich sie auf meinem Balkon heran, um sie für das eingereichte Bild zu malen.",
    "descriptionEn": "In preparing for the exhibition, I found that various wild Lathyrus forms are threatened, and some even critically endangered. To counter wild seed collecting, many cultivated varieties are available. I love the bizarre flowers in their many colors, so I grew them on my balcony to paint this piece.",
    "author": "Margitta Baum",
    "plantCommonName": "Platterbse",
    "plantCommonNameEn": "Pea-vine (Lathyrus)",
    "plantBotanicalName": "Lathyrus sp.",
    "artworkYear": "2025",
    "artworkSize": "30×40cm",
    "artworkTechnique": "Aquarell / Papier",
    "artworkTechniqueEn": "Watercolor / paper",
    "lowSrc": "/src/thumbs/33.jpg",
    "lowWidth": 400,
    "lowHeight": 523
  },
  {
    "src": "/src/img/34.jpg",
    "width": 1800,
    "height": 2592,
    "title": "Die Früchte des Olivenbaums",
    "titleEn": "The Fruits of the Olive Tree",
    "description": "Obwohl der Olivenbaum noch nicht auf der Liste der gefährdeten Arten steht, ist er durch verschiedene Faktoren bedroht.\nOlivenbäume können mehrere hundert Jahre alt werden. Das Olivebaumsterben wurde in Europa zuerst in Süditalien festgestellt. Auch andere südeuropäische Länder wie Spanien, Griechenland, Portugal und die Türkei hatten ähnliche Probleme. Leider wurde die Ernte aufgrund extremer Hitze, Wassermangel und Schädlingen in den vergangenen Sommern stark beeinträchtigt. Während der Blütezeit führte die Hitze zum Austrocknen der Blütenstände. Die extremen Wetterbedingungen im Sommer verhindern, dass die Früchte reifen und das Öl unter kühleren und feuchteren Bedingungen gebildet wird. Hinzu kommt, dass Waldbrände die Olivenhaine vernichten. Und dann ist da natürlich noch der tödliche bakterielle Krankheitserreger, Xylella fastidiosa, der die Ernte bedroht. Die Bäume ersticken schließlich, verdorren und vertrocknen. Die einst frühen Blätter fallen ab, und die Rinde vergraut und hinterlässt eine Spur des Todes. Millionen von Olivenbäumen wurden dadurch vernichtet, insbesondere in Italien und Spanien. In den Jahren 2022/2023 und 2023/2024 ging die Olivenölproduktion in der EU stark zurück. Der Anstieg der Olivenölpreise in unseren Supermärkten spiegelt die Tragödie der Olivenernte in den betroffenen Regionen wider. Derzeit laufen Forschungs- und Entwicklungsarbeiten, um das Problem von Xylella fastidiosa zu lösen.\n(Quellen: https://bbc.com accessscience.com theguardian.org en.wikipedia.org nature.com https://wearewater.org)",
    "descriptionEn": "Although not yet listed as endangered, the olive tree faces multiple threats — extreme heat, water scarcity, pests, wildfires, and the bacterial pathogen Xylella fastidiosa. Millions of trees have been lost, especially in Italy and Spain; EU olive oil production fell sharply in 2022/2023 and 2023/2024, and rising prices reflect harvest losses in affected regions. Research is underway to address Xylella fastidiosa.",
    "author": "Sue Hénon",
    "plantCommonName": "Olive",
    "plantCommonNameEn": "Olive",
    "plantBotanicalName": "Olea europaea",
    "artworkYear": "2024",
    "artworkSize": "50×70cm",
    "artworkTechnique": "Farbstift und Graphit auf Papier",
    "artworkTechniqueEn": "Colored pencil and graphite on paper",
    "contactEmail": "atelierhenon@googlemail.com",
    "lowSrc": "/src/thumbs/34.jpg",
    "lowWidth": 400,
    "lowHeight": 576
  },
  {
    "src": "/src/img/35.jpg",
    "width": 1800,
    "height": 2546,
    "title": "Sanddorn ",
    "titleEn": "Sea Buckthorn",
    "description": "Der Sanddorn ist eine charakteristische Pflanze der Küstenregionen Deutschlands und besiedelt vor allem die Graudünen. Dieser Lebensraum ist jedoch zunehmend gefährdet: Küstenschutzmaßnahmen wie Eindeichungen, die intensive touristische Nutzung mit Trittschäden und Abfall sowie die Verdrängung durch die invasive Kartoffelrose bedrohen den Bestand der Graudünen und damit auch den Sanddorn selbst.",
    "descriptionEn": "Sea buckthorn is characteristic of Germany’s coastal regions, colonizing grey dunes. These habitats are threatened by coastal protection measures, intensive tourism, and displacement by the invasive rugosa rose.",
    "author": "Yana Andryeyeva",
    "plantCommonName": "Sanddorn",
    "plantCommonNameEn": "Sea Buckthorn",
    "plantBotanicalName": "Hippophae rhamnoides",
    "artworkYear": "2025",
    "artworkSize": "30×40cm",
    "artworkTechnique": "Aquarell auf Papier (Echt-Bütten von Hahnemühle, hot pressed, satiniert, 600 g/m², ",
    "artworkTechniqueEn": "Watercolor on paper (Hahnemühle mould-made, hot pressed, satinated, 600 g/m²)",
    "contactEmail": "info@andryeyeva.de",
    "contactSocial": "@andryeyevart (Instagram)",
    "lowSrc": "/src/thumbs/35.jpg",
    "lowWidth": 400,
    "lowHeight": 566
  }
];
