export const galleryPhotos = [
  {
    "src": "/src/img/1.jpg",
    "width": 3988,
    "height": 5728,
    "title": "Herbst II",
    "description": " Verbreitungsgebiet Südwest-Türkei und auf Rhodos. In Parks in der Türkei und auf Rhodos ist er durch das Fällen von Bäumen für Straßen, Staudämme und die Landwirtshaft gefährdet. Touristen und Bauindustrie sind seine Feinde.",
    "author": "Sue Hénon",
    "plantCommonName": "Orientalischer Amberbaum",
    "plantBotanicalName": "Liquidambar orientalis",
    "artworkYear": "2024",
    "artworkSize": "50×70cm",
    "artworkTechnique": "Farbstift auf Papier",
    "contactEmail": "atelierhenon@googlemail.com",
    "contactPhone": "06071-21613",
    "lowSrc": "/src/thumbs/1.jpg",
    "lowWidth": 400,
    "lowHeight": 575
  },
  {
    "src": "/src/img/2.jpg",
    "width": 7016,
    "height": 9921,
    "title": "Aerangis Punctata",
    "description": "Aerangis punctata ist eine seltene, auf Bäumen wachsende Orchidee aus den feuchten Hochwäldern Madagaskars. Ihr zartes Gleichgewicht mit dem Lebensraum ist durch Abholzung und Klimaveränderungen bedroht. Um die wenigen verbliebenen Populationen zu schützen, steht sie heute als gefährdete Art (vulnerable) unter internationalem Schutz.",
    "author": "Kristin Tessen",
    "plantCommonName": "gepunktete Aerangis",
    "plantBotanicalName": "Aerangis punctata ",
    "artworkYear": "2025",
    "artworkSize": "29.7×42cm",
    "artworkTechnique": "Aquarell",
    "contactWebsite": "https://www.instagram.com/kristintessen/",
    "lowSrc": "/src/thumbs/2.jpg",
    "lowWidth": 400,
    "lowHeight": 566
  },
  {
    "src": "/src/img/3.jpg",
    "width": 2480,
    "height": 3508,
    "title": "Round leaved sundew",
    "description": "Drosera rotundifolia, der Rundblättrige Sonnentau, ist eine mehrjährige, fleischfressende Pflanze. Sie besiedelt offene, feuchte und nährstoffarme Standorte wie saure Hochmoore und wächst insbesondere in Pflanzengesellschaften, die von Torfmoosen (Sphagnum) dominiert werden.\n\nHochmoore reagieren äußerst empfindlich auf Veränderungen. Entwässerung und Nährstoffeintrag zerstören ihre ökologische Funktion für Artenschutz und Klima. Die Zerstörung in kurzer Zeit machte zunichte, was über Jahrtausende entstand. Die Wiederherstellung der Moore zielt daher auf natürliche Bedingungen – vor allem einen intakten Wasserhaushalt – und benötigt gezielte Impulse und viel Zeit.\n",
    "author": "Audrey Reilly",
    "plantCommonName": "Rundblättriger Sonnentau",
    "plantBotanicalName": "Drosera rotundifolia L.",
    "artworkYear": "2024",
    "artworkSize": "34×41cm",
    "artworkTechnique": "Aquarell auf Papier",
    "contactWebsite": "www.audreyreilly-art.com",
    "contactSocial": "@audrey.reilly",
    "lowSrc": "/src/thumbs/3.jpg",
    "lowWidth": 400,
    "lowHeight": 566
  },
  {
    "src": "/src/img/4.jpg",
    "width": 2480,
    "height": 3508,
    "title": "Bog rosemary",
    "description": "Andromeda polifolia, die Rosmarinheide, wächst ausschließlich in Hochmooren kälterer Regionen. Der kleine, immergrüne Zwergstrauch mit zierlichen rosa Blüten ist in den nördlichen Gebieten Nordamerikas, Asiens und Europas verbreitet.\n\nIhr Bestand geht jedoch stark zurück - in England und Irland ist die Art bereits stark dezimiert. Der Lebensraum Hochmoor hat unter Entwässerung, Aufforstung und Torfabbau gelitten, was die Rosmarinheide immer seltener werden lässt. Ihr Verschwinden in Westeuropa ist meist eine direkte Folge der Moorentwässerung.\n\nHochmoore reagieren äußerst empfindlich. Entwässerung zerstört ihre ökologische Funktion für Artenschutz und Klima. Was über Jahrtausende entstand, wurde in kurzer Zeit zerstört. Die Wiederherstellung der Moore benötigt daher natürliche Bedingungen – vor allem einen intakten Wasserhaushalt – und braucht gezielte Maßnahmen sowie viel Zeit.\n",
    "author": "Audrey Reilly",
    "plantCommonName": "Rosmarinheide",
    "plantBotanicalName": "Andromeda polifolia",
    "artworkYear": "2024",
    "artworkSize": "34×41cm",
    "artworkTechnique": "Aquarell auf Papier",
    "contactWebsite": "www.audreyreilly-art.com",
    "lowSrc": "/src/thumbs/4.jpg",
    "lowWidth": 400,
    "lowHeight": 566
  },
  {
    "src": "/src/img/5.jpg",
    "width": 2373,
    "height": 2925,
    "title": "Purple Marshlock (Blume des Jahres 2025)",
    "description": "Das Sumpf-Blutauge kommt vom Tiefland bis ins Gebirge vor und besiedelt bevorzugt nasse, zeitweise überflutete Torf- und Schlammböden in Niedermooren. Es gedeiht besonders auf offenen Schlammstellen, wo es sich mit seinem langen Wurzelstock gut ausbreiten kann. Sogar auf Schwingrasen bildet es allmählich schwankende Teppiche auf der Wasseroberfläche mooriger Gewässer.\n\nAls Spezialist für den stark bedrohten Lebensraum Moor steht die Art in vielen Regionen auf der Roten Liste. Die Loki Schmidt Stiftung hat sie zur Blume des Jahres 2025 ernannt.\n\nHochmoore reagieren äußerst empfindlich auf Störungen. Entwässerung und Nährstoffeintrag zerstören ihre ökologischen Funktionen für Artenschutz und Klima. Was über Jahrtausende entstand, wurde in kurzer Zeit zerstört. Die Wiederherstellung der Moore zielt daher auf natürliche Bedingungen – besonders einen intakten Wasserhaushalt – und benötigt gezielte Maßnahmen und viel Zeit.",
    "author": "Audrey Reilly",
    "plantCommonName": "Blutauge, Sumpf-Fingerkraut",
    "plantBotanicalName": "Comarum palustre",
    "artworkYear": "2024",
    "artworkSize": "40×50cm",
    "artworkTechnique": "Aquarell auf Papier",
    "contactWebsite": "www.audreyreilly-art.com",
    "lowSrc": "/src/thumbs/5.jpg",
    "lowWidth": 400,
    "lowHeight": 493
  },
  {
    "src": "/src/img/6.jpg",
    "width": 2048,
    "height": 1536,
    "title": "Echte Lungenflechte ",
    "description": "Durch Luftverschmutzung und die Zerstörung ihrer Lebensräume u. a. durch intensive forstwirtschaftliche Nutzung steht die Echte Lungenflechte mittlerweile in Deutschland auf der Roten Liste und gilt als \"Vom Aussterben bedroht\".\nDenn sie benötigt sehr saubere Luft, alte Bäume und eine hohe Luftfeuchtigkeit, um zu gedeihen. ",
    "author": "Katrin Koch ",
    "plantCommonName": "Echte Lungenflechte ",
    "plantBotanicalName": "Lobaria pulmonaria ",
    "artworkYear": "2025",
    "artworkSize": "7.5×26cm",
    "artworkTechnique": "Graphit und Farbstift auf Papier /Fabriano Artistico Hot Pressed \"Extra White\" ",
    "contactEmail": "malusred@gmx.de",
    "lowSrc": "/src/thumbs/6.jpg",
    "lowWidth": 533,
    "lowHeight": 400
  },
  {
    "src": "/src/img/9.png",
    "width": 4320,
    "height": 5400,
    "title": "Der Stern der Alpen",
    "description": "Das Edelweiß ist in seinem natürlichen Lebensraum nach wie vor durch übertriebenes Pflücken bedroht. An vielen leicht zugänglichen Standorten war es dadurch fast ausgestorben. Seit die Art in vielen Ländern und Regionen unter Naturschutz steht, haben sich die Bestände in der freien Natur erholt. Die wilden Pflanzen sind jedoch nach wie vor durch unkontrolliertes Sammeln und Lebensraumverlust bedroht.\n\nDie Pflanze wird gerne in vielen Gärten kultiviert. Kulturpflanzen sehen im Vergleich zu Wildpflanzen meist anders aus. Sie sind oft deutlich höher und weniger weiß behaart. Die hier abgebildete Pflanze ist ein Kulturexemplar.",
    "author": "Maxim Shirshin",
    "plantCommonName": "Alpen-Edelweiß",
    "plantBotanicalName": "Leontopodium nivale",
    "artworkYear": "2025",
    "artworkSize": "21×29.7cm",
    "artworkTechnique": "Buntstifte auf Papier",
    "contactPhone": "+447376444778",
    "contactEmail": "max.shirshin@gmail.com",
    "contactSocial": "max.shirshin",
    "lowSrc": "/src/thumbs/9.png",
    "lowWidth": 400,
    "lowHeight": 500
  },
  {
    "src": "/src/img/13.jpg",
    "width": 3345,
    "height": 4181,
    "title": "Frauenschuh",
    "description": "Der Frauenschuh gilt nach der Roten Liste als gefährdet und ist nach der Bundesartenschutzverordnung streng geschützt. Er steht auch unter besonderem Schutz der Europäischen Union. \nAls ursächlich für die Gefährdung wird vor allem die weitreichende Forstwirtschaft gesehen, die eine natürliche Waldentwicklung und -dynamik kaum zulässt. Fototourismus trägt zu einem Rückgang der Art bei, da der Boden sich durch häufiges Betreten verdichtet und dadurch neuen Exemplaren eine Ansiedlung erschwert wird. \nAuch Pflanzenliebhaber, die den Frauenschuh ausgraben, tragen wesentlich zum Rückgang der verbliebenen Vorkommen bei.\n (Vgl. https://de.wikipedia.org/wiki/Gelber_Frauenschuh, 08.10.2025)",
    "author": "Leslie Bocker",
    "plantCommonName": "Frauenschuh",
    "plantBotanicalName": "Cypripedium calceolus L.",
    "artworkYear": "2025",
    "artworkSize": "25×50cm",
    "artworkTechnique": "Aquarell",
    "contactSocial": "leslie.bocker",
    "lowSrc": "/src/thumbs/13.jpg",
    "lowWidth": 400,
    "lowHeight": 500
  },
  {
    "src": "/src/img/15.jpg",
    "width": 3386,
    "height": 2709,
    "title": "Kastanie",
    "description": "Die Rosskastanie hierzulande hat gleich mit mehreren Problemen auf einmal zu kämpfen: Zum einen mit der sogenannten Miniermotte, zum anderen mit einem Bakterium namens Pseudomonas. Auch der Klimawandel stresst die Bäume zunehmend. Die Weltnaturschutzunion (IUCN) hat die Gewöhnliche Rosskastanie deshalb mittlerweile als \"gefährdet\" eingestuft.\n( https://www.oekotest.de/freizeit-technik/Kastanienblaetter-schon-im-Sommer-braun-So-reagieren-Sie-richtig_12142_1.html, 25.09.2025)",
    "author": "Leslie Bocker",
    "plantCommonName": "Gewöhnliche Rosskastanie",
    "plantBotanicalName": "Aesculus hippocastanum",
    "artworkYear": "2024",
    "artworkSize": "25×23cm",
    "artworkTechnique": "Aquarell",
    "contactSocial": "leslie.bocker",
    "lowSrc": "/src/thumbs/15.jpg",
    "lowWidth": 500,
    "lowHeight": 400
  },
  {
    "src": "/src/img/16.jpg",
    "width": 3620,
    "height": 4802,
    "title": "Maiglöckchen",
    "description": "Diese zarte Blume wächst in vielen europäischen Ländern in der freien Natur, jedoch ist die Anzahl der Pflanzen sehr gering. In vielen Ländern ist das Pfücken der Blumen verboten, wie z.B. im Ruhrgebiet in Deutschland. Obwohl in Deutschland kleine Sträußchen für den Eigenbedarf erlaubt sind, ist das Ausgraben der unterirdischen Teile wie der Rhizome in der freien Natur untersagt, um die Bestände zu erhalten. ",
    "author": "Nadiya Kyrylenko",
    "plantCommonName": "Maiglöckchen",
    "plantBotanicalName": "Convallaria majalis",
    "artworkYear": "2025",
    "artworkSize": "30×40cm",
    "artworkTechnique": "Mischtechnik: Aquarell und Bleistift",
    "contactPhone": "01791314354",
    "contactWebsite": "https://www.instagram.com/nadiya_kyrylenko/",
    "lowSrc": "/src/thumbs/16.jpg",
    "lowWidth": 400,
    "lowHeight": 531
  },
  {
    "src": "/src/img/17.jpg",
    "width": 6596,
    "height": 6660,
    "title": "Stille der Frühlingswiesen",
    "description": "Schachblume (Fritillaria meleagris)\nAquarell und Graphit auf Papier\n\nEine seltene, in Deutschland geschützte Art.\nIhre natürlichen Lebensräume – feuchte Wiesen und Flussauen – verschwinden nach und nach, und mit ihnen verschwindet auch die Schachblume.\nZart und zugleich widerstandsfähig verkörpert sie die Idee des Überlebens durch Sanftheit.\nDiese Arbeit ist eine Hommage an ihre stille Schönheit und ihre flüchtige Präsenz in der Natur.",
    "author": "Lesia Zaitseva",
    "plantCommonName": "Schachblume (Fritillaria meleagris)",
    "plantBotanicalName": "Fritillaria meleagris",
    "artworkYear": "2025",
    "artworkSize": "56×56cm",
    "artworkTechnique": "Aquarell und Graphit auf Papier Saunders Waterford HP 425 g/m²",
    "contactSocial": "Lesia_botanicalart",
    "lowSrc": "/src/thumbs/17.jpg",
    "lowWidth": 400,
    "lowHeight": 404
  },
  {
    "src": "/src/img/18.jpg",
    "width": 2600,
    "height": 3478,
    "title": "Lion's Tooth (Deutscher Löwenzahn)",
    "description": "Der deutsche Löwenzahn (Taraxacum germanium), einst Teil der einheimischen Flora Deutschlands, ist heute vom Aussterben bedroht und überlebt nur noch an wenigen verstreuten Standorten in Hessen, Unterfranken und Oberbayern. Die meisten dieser Populationen bestehen aus nur wenigen einzelnen Pflanzen und überschreiten selten fünfzig Exemplare. Diese Art gedeiht in Niederungs-Feuchtwiesen, oft auf leicht salzhaltigen Böden, doch ihre Empfindlichkeit gegenüber Düngung und Störungen des Lebensraums hat sie äußerst verletzlich gemacht. Landwirtschaftliche Intensivierung, Lebensraumverlust und Verschmutzung haben sie an den Rand des Aussterbens gedrängt.\n\nWährend der Gewöhnliche Löwenzahn (Taraxacum officinale) heute noch weit verbreitet ist, werden auch seine natürlichen Lebensräume zunehmend durch ähnliche Bedrohungen – Herbizideinsatz, Monokultur-Landwirtschaft, städtische Bebauung und den Klimawandel – beeinträchtigt. Wenn diese Belastungen anhalten, könnte selbst diese widerstandsfähige und weit verbreitete Pflanze dem Beispiel des deutschen Löwenzahns folgen und zurückgehen – ein mahnendes Zeichen dafür, dass keine Art vor den Folgen menschengemachter Umweltveränderungen gefeit ist.",
    "author": "Kate Rolshoven",
    "plantCommonName": "Deutscher Löwenzahn",
    "plantBotanicalName": "Taraxacum germanicum",
    "artworkYear": "2023",
    "artworkSize": "56×76cm",
    "artworkTechnique": "Aquarell on Arches 640gsm Baumwollpapier",
    "contactWebsite": "www.katerolshovenart.com",
    "contactSocial": "katerolshovenart",
    "lowSrc": "/src/thumbs/18.jpg",
    "lowWidth": 400,
    "lowHeight": 535
  },
  {
    "src": "/src/img/19.jpg",
    "width": 9920,
    "height": 7014,
    "title": "Beta vulgaris",
    "description": "Die wilde Rübe die Urpflanze unseres heutigen Mangolds und der Roten Bete. Die Wildform gilt in Deutschland als potenziell gefährdet. Auf Helgoland, wo sie früher weit verbreitet war, gibt es noch einige wenige Bestände. Die Beta vulgaris wurde sonst nur noch an einigen Orten an der Ostseeküste verzeichnet.",
    "author": "Manuela Herhaus",
    "plantCommonName": "Wilde Rübe",
    "plantBotanicalName": "Beta vulgaris",
    "artworkYear": "2025",
    "artworkSize": "30×42cm",
    "artworkTechnique": "Tusche auf Zeichenfolie mit Beschreibung auf Papier",
    "contactEmail": "herhaus@wortimpulse.de",
    "lowSrc": "/src/thumbs/19.jpg",
    "lowWidth": 566,
    "lowHeight": 400
  },
  {
    "src": "/src/img/22.jpg",
    "width": 3400,
    "height": 3425,
    "title": "Deutsche Ufertamariske",
    "description": "In Bayern vom Aussterben bedroht.",
    "author": "Elisabeth Lázár ",
    "plantCommonName": "Deutsche Ufertamariske",
    "plantBotanicalName": "Myricaria germanica",
    "artworkYear": "2025",
    "artworkSize": "29×29cm",
    "artworkTechnique": "Graphit, Papier",
    "lowSrc": "/src/thumbs/22.jpg",
    "lowWidth": 400,
    "lowHeight": 403
  },
  {
    "src": "/src/img/23.png",
    "width": 2484,
    "height": 3155,
    "title": "Karlszepter-Läusekraut",
    "description": "In Bayern stark gefährdet.",
    "author": "Elisabeth Lázár",
    "plantCommonName": "Karlszepter-Läusekraut",
    "plantBotanicalName": "Pedicularis sceptrum-carolinum L.",
    "artworkYear": "2025",
    "artworkSize": "21×27cm",
    "artworkTechnique": "Tinte, Papier",
    "lowSrc": "/src/thumbs/23.png",
    "lowWidth": 400,
    "lowHeight": 508
  },
  {
    "src": "/src/img/24.jpg",
    "width": 3345,
    "height": 4943,
    "title": "Karlszepter-Läusekraut",
    "description": "In Bayern stark gefährdet ",
    "author": "Elisabeth Lázár ",
    "plantCommonName": "Karlszepter-Läusekraut",
    "plantBotanicalName": "Pedicularis sceptrum-carolinum L.",
    "artworkYear": "2025",
    "artworkSize": "28×42cm",
    "artworkTechnique": "Aquarell, Graphit, Papier",
    "lowSrc": "/src/thumbs/24.jpg",
    "lowWidth": 400,
    "lowHeight": 591
  },
  {
    "src": "/src/img/25.jpg",
    "width": 1365,
    "height": 2048,
    "title": "Geweihförmige Wiesenkoralle ",
    "description": "Durch die intensive Nutzung ihres speziellen Lebensraumes - dem Magerrasen, gingen die Bestände dieser Art in den letzten Jahrzehnten deutlich zurück und die Geweihförmige Wiesenkoralle steht mittlerweile als \"Gefährdet\" auf der Roten Liste in Deutschland.\nDenn Überdüngung, Bebauung und Überwässerung verändert ihr Ökosystem und so ist der Lebensraum mittlerweile nur noch selten in unserer Landschaft zu finden. ",
    "author": "Katrin Koch ",
    "plantCommonName": "Geweihförmige Wiesenkoralle ",
    "plantBotanicalName": "Clavulinopsis corniculata",
    "artworkYear": "2025",
    "artworkSize": "11×11.8cm",
    "artworkTechnique": "Farbstift auf Papier /Fabriano Artistico Hot Pressed \"Extra White\" ",
    "contactEmail": "malusred@gmx.de",
    "lowSrc": "/src/thumbs/25.jpg",
    "lowWidth": 400,
    "lowHeight": 600
  },
  {
    "src": "/src/img/26.jpg",
    "width": 9284,
    "height": 7020,
    "title": "Vom Blühen und Reifen",
    "description": "Die Preiselbeere steht unter Druck: Durch den Rückgang naturnaher Moore und lichter Nadelwälder verliert sie zunehmend ihren Lebensraum. Entwässerung, Forstwirtschaft und der Klimawandel setzen ihren Beständen zu – vielerorts gilt sie deshalb bereits als gefährdet.",
    "author": "Daria Beizerov",
    "plantCommonName": "Preiselbeere",
    "plantBotanicalName": "Vaccinium vitis-idaea",
    "artworkYear": "2025",
    "artworkSize": "41×31cm",
    "artworkTechnique": "Aquarell auf Papier (HP)",
    "contactWebsite": "https://www.instagram.com/daria.botanicals/",
    "lowSrc": "/src/thumbs/26.jpg",
    "lowWidth": 529,
    "lowHeight": 400
  },
  {
    "src": "/src/img/28.jpg",
    "width": 3850,
    "height": 4695,
    "title": "Weiße Schlauchpflanze",
    "description": "Die Weiße Schlauchpflanze (Sarracenia leucophylla) kommt ursprünglich im Südosten der Vereinigten Staaten vor, insbesondere in Alabama, Georgia, Florida und Mississippi. Obwohl sie dort noch in der Wildnis vorkommt, ist sie durch das Sammeln zu Dekorationszwecken und durch Landentwicklung bedroht. Daher ist sie in der Roten Liste der bedrohten Arten der IUCN aufgeführt. Als Zimmerpflanze ist sie beliebt, weil sie mit ihren auffällig gezeichneten Schläuchen und ihrer Fähigkeit, Insekten zu fangen, ein außergewöhnliches und dekoratives Element darstellt.",
    "author": "Sophie Crossart",
    "plantCommonName": "Weiße Schlauchpflanze",
    "plantBotanicalName": "Sarracenia leucophylla",
    "artworkYear": "2025",
    "artworkSize": "17×20cm",
    "artworkTechnique": "Aquarell und ein wenig Gouache auf Kalbsvellum",
    "contactEmail": "contact@sophiecrossart.com",
    "contactWebsite": "www.sophiecrossart.com",
    "contactSocial": "sophiecrossart",
    "lowSrc": "/src/thumbs/28.jpg",
    "lowWidth": 400,
    "lowHeight": 487
  },
  {
    "src": "/src/img/29.png",
    "width": 3508,
    "height": 4963,
    "title": "Zahnbürstchenwiese",
    "description": "Der Schlangenknöterich ist eine typische Pflanze feuchter, artenreicher Lebensräume. Er wächst bevorzugt in Feuchtwiesen, an den Ufern von Bächen, an Moorrändern sowie in lichten Auwäldern. Doch sind diese Lebensräume zunehmend im Rückgang begriffen. \nTrockenlegungen, intensive Bewirtschaftung durch die Landwirtschaft und das Verschwinden naturnaher Auwälder führen zum Verlust geeigneter Standorte. \nHinzu kommen die Auswirkungen des Klimawandels.\nDer Schlangenknöterich steht in Bayern auf Platz 3 der Gefährdungsliste.\nSo wird er zunehmend zum Symbol für die bedrohte Schönheit unserer Feuchtlandschaften.",
    "author": "Susanne Jampen",
    "plantCommonName": "Schlangenknöterich",
    "plantBotanicalName": "Bistorta officinalis",
    "artworkYear": "Sommer 2025",
    "artworkSize": "20×32cm",
    "artworkTechnique": "Aquarell auf Fabriano artistico hot press",
    "contactEmail": "s.jampen@icloud.com",
    "lowSrc": "/src/thumbs/29.png",
    "lowWidth": 400,
    "lowHeight": 566
  },
  {
    "src": "/src/img/30.jpg",
    "width": 2308,
    "height": 3003,
    "title": "Sumpf-Herzblatt",
    "description": "Diese seltene Pflanze gehört zu den Steinbrech-Gewächsen und steht auf der Roten Liste Bayerns und gilt als gefährdet. Ursache für die Gefährdung der Pflanze sind etwa die Entwässerung und Aufforstung von Moor-Standorten oder Trockenlegungen von Feuchtwiesen. Aber auch durch die Eutrophierungen, sprich Dünger-Eintragungen, werde die konkurrenzschwache Art zurückgedrängt (https://pfaffenhofen-today.de/46272-p-serie-sumpf-herzblatt. 08.10.2025)",
    "author": "Leslie Bocker",
    "plantCommonName": "Sumpf-Herzblatt",
    "plantBotanicalName": "Parnassia palustris",
    "artworkYear": "2025",
    "artworkSize": "31×39cm",
    "artworkTechnique": "Aquarell",
    "contactSocial": "leslie.bocker",
    "lowSrc": "/src/thumbs/30.jpg",
    "lowWidth": 400,
    "lowHeight": 520
  },
  {
    "src": "/src/img/31.jpg",
    "width": 1427,
    "height": 2008,
    "title": "Die Geneigte",
    "description": "Die Bach-Nelkenwurz ist eine typische Pflanze in feuchten Lebensräumen. Sie wächst in Flachmooren, Feuchtwiesen, an Bächen und Teichufern und am Rande von Auwäldern.\nTrotz ihres ursprünglich großen Verbreitungsareals gilt die Bach-Nelkenwurz in mehreren deutschen Bundesländern mittlerweile als gefährdet und ist dort auf den regionalen roten Listen verzeichnet. \nDie Hauptursachen dafür liegen in der Zerstörung und Veränderung der Lebensräume.\nDie Trockenlegung von Feuchtgebieten, die Intensivnutzung der Wiesen, und das Verschwinden der naturnahen Auwälder führen zu einem drastischen Rückgang der Standorte. Dazu kommen die durch den Klimawandel veränderten Niederschlagsmuster und die steigenden Temperaturen, die zur Austrocknung der Lebensräume beitragen.",
    "author": "Susanne Jampen",
    "plantCommonName": "Bach-Nelkenwurz",
    "plantBotanicalName": "Geum rivale",
    "artworkYear": "Sommer 2024",
    "artworkSize": "20×32cm",
    "artworkTechnique": "Aquarell auf Fabriano Artistico hot pressd ",
    "contactEmail": "s.jampen@icloud.com",
    "lowSrc": "/src/thumbs/31.jpg",
    "lowWidth": 400,
    "lowHeight": 563
  },
  {
    "src": "/src/img/32.jpg",
    "width": 3386,
    "height": 3002,
    "title": "Enzian",
    "description": "Die Pflanze ist in Deutschland nur in den Alpen anzutreffen. Gentiana acaulis steht wie alle Enzianarten unter Naturschutz und ist als \"gefährdet\" einestuft.(Rote Liste  Zentrum)",
    "author": "Brigitte Rückle",
    "plantCommonName": "Kiesel-Glocken-Enzian",
    "plantBotanicalName": "Gentiana acaulis",
    "artworkYear": "2025",
    "artworkSize": "31.5×29.5cm",
    "artworkTechnique": "Buntstifte ",
    "contactNote": "Brigitte Rückle c/ o VBKD",
    "lowSrc": "/src/thumbs/32.jpg",
    "lowWidth": 451,
    "lowHeight": 400
  },
  {
    "src": "/src/img/33.jpg",
    "width": 2752,
    "height": 3246,
    "title": "Platterbse/ Duftwicke",
    "description": "Verschiedene Naturformen der Platterbse stehen auf der Roten Liste der Farn u. Blütenpflanzen der TU Berlin. ",
    "author": "Margitta Baum",
    "plantCommonName": "Platterbse",
    "plantBotanicalName": "Lathyrus sp.",
    "artworkYear": "2025",
    "artworkSize": "30×40cm",
    "artworkTechnique": "Aquarell / Papier",
    "lowSrc": "/src/thumbs/33.jpg",
    "lowWidth": 400,
    "lowHeight": 472
  },
  {
    "src": "/src/img/34.jpg",
    "width": 278,
    "height": 400,
    "title": "Die Früchte des Olivenbaums",
    "description": "Das Olivenbaumsterben wurde in Europa zuerst in Süditalien festgestellt. Ursache - das Bakterium Xylella fastidiosa. Abgesehen davon wurden die Olivenhaine durch die Waldbrände in Südeuropa stark in Mitleidenschaft gezogen.  Dies lässt sich auch an den höheren Olivenölpreisen den Supermärkten erkennen.",
    "author": "Sue Hénon",
    "plantCommonName": "Olive",
    "plantBotanicalName": "Olea europaea",
    "artworkYear": "2024",
    "artworkSize": "50×70cm",
    "artworkTechnique": "Farbstift und Graphit auf Papier",
    "contactEmail": "atelierhenon@googlemail.com",
    "lowSrc": "/src/thumbs/34.jpg",
    "lowWidth": 400,
    "lowHeight": 576
  },
  {
    "src": "/src/img/35.jpg",
    "width": 2480,
    "height": 3508,
    "title": "Sanddorn ",
    "description": "Der Sanddorn wächst in Graudünen, deren Fortbestand durch äußere Einflüsse – unter anderem Abfälle und Trittschäden – beeinträchtigt wird. An vielen Orten wird der Sanddorn durch die Ausbreitung der nichtheimischen Kartoffelrose seines Lebensraums beraubt.",
    "author": "Yana Andryeyeva",
    "plantCommonName": "Sanddorn",
    "plantBotanicalName": "Hippophae rhamnoides",
    "artworkYear": "2025",
    "artworkSize": "30×40cm",
    "artworkTechnique": "Aquarell auf Papier (Echt-Bütten von Hahnemühle, hot pressed, satiniert, 600 g/m², ",
    "contactEmail": "info@andryeyeva.de",
    "contactSocial": "@andryeyevart (Instagram)",
    "lowSrc": "/src/thumbs/35.jpg",
    "lowWidth": 400,
    "lowHeight": 566
  }
];
